import localFont from "next/font/local"
import "./globals.css"
import { SpeedInsights } from "@vercel/speed-insights/next"
const arial = localFont({
  src: [
    {
      path: "../assets/arial-font/arial.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/arial-font/G_ari_i.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../assets/arial-font/G_ari_bd.ttf",
      weight: "400",
      style: "bold",
    },
    {
      path: "../assets/arial-font/arial.ttf",
      weight: "700",
      style: "normal",
    },
  ],
})

export const metadata = {
  title: "Digital Technology",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={arial.className}>
      <body>
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
