name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - staging  # Menjalankan workflow pada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build and export Next.js app
    - name: Build and export Next.js
      run: npm run deploy

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages  # Nama branch untuk GitHub Pages
        folder: out  # Folder output dari next export
